import type { AppState } from '../store/types';

export const DEFAULT_STATE: AppState = {
  activeProject: 0,
  supabaseIds: [],
  projects: [
    {
      config: {
        clientName: 'Project Ascend',
        ehr: 'Epic',
        ehrCustom: '',
        engagementType: 'Implementation',
        projectStatus: 'On Track',
        startDate: '2026-01-05',
        managingDirector: 'David Marsh, Managing Director',
        lead: 'Sarah Callahan, Senior Director',
        payers: ['Blue Cross', 'Aetna', 'UnitedHealthcare', 'Humana', 'Medicare', 'Medicaid'],
        denials: ['Auth Not Obtained', 'Medical Necessity', 'Eligibility', 'COB', 'Timely Filing'],
        roles: [
          { key: 'Auth Lead',           clientRole: 'Authorization Manager' },
          { key: 'Billing Director',    clientRole: 'Director of Patient Accounts' },
          { key: 'AR Manager',          clientRole: 'AR Supervisor' },
          { key: 'Patient Access Dir.', clientRole: 'VP of Patient Access' },
          { key: 'HIM / Coding',        clientRole: 'HIM Director' },
          { key: 'IT / IS Lead',        clientRole: 'Epic Principal Trainer' },
        ],
        workstreams: [
          { id: 'auth',    label: 'Authorization',  color: 'blue',   amOwner: 'Marcus Webb' },
          { id: 'billing', label: 'Billing',         color: 'green',  amOwner: 'Priya Nair' },
          { id: 'access',  label: 'Patient Access',  color: 'purple', amOwner: 'James Okafor' },
          { id: 'coding',  label: 'Coding',          color: 'amber',  amOwner: 'Priya Nair' },
          { id: 'ar',      label: 'AR Management',   color: 'coral',  amOwner: 'Marcus Webb' },
        ],
      },
      milestones: [
        {
          id: '10000000-0000-0000-0000-000000000001', title: 'Prior authorization workflow consolidation',
          workstream: 'auth', status: 'inprogress', owner: 'Auth Lead', dueDate: '2026-04-30',
          tasks: [
            { id: 'a1', text: 'Map current authorization responsibility by payer and specialty', done: true,  startDate: '2026-01-06', endDate: '2026-01-17', note: '', owner: 'Marcus Webb', subtasks: [], predecessors: [] },
            { id: 'a2', text: 'Identify specialties with highest prior auth denial rates – Wave 1 targets', done: true,  startDate: '2026-01-13', endDate: '2026-01-31', note: '', owner: 'Marcus Webb', subtasks: [], predecessors: [] },
            { id: 'a3', text: 'Build payer/specialty matrix and centralized auth tracking workqueue', done: true,  startDate: '2026-02-03', endDate: '2026-02-21', note: '', owner: 'Marcus Webb', subtasks: [], predecessors: [] },
            { id: 'a4', text: 'Finalize FTE model and staffing plan for centralized auth team', done: false, startDate: '2026-02-17', endDate: '2026-03-14', note: '', owner: 'Sarah Callahan', subtasks: [], predecessors: ['a3'] },
            { id: 'a5', text: 'Develop authorization tracking dashboard and real-time workqueue views', done: false, startDate: '2026-03-09', endDate: '2026-03-28', note: '', owner: 'Marcus Webb', subtasks: [], predecessors: [] },
            { id: 'a6', text: 'Go-live readiness checklist, staff training, and sign-off', done: false, startDate: '2026-03-30', endDate: '2026-04-30', note: '', owner: 'Sarah Callahan', subtasks: [], predecessors: ['a4', 'a5'] },
          ],
          impact: [
            { type: 'Authorization Rate',    projected: '+12%',  realized: '' },
            { type: 'Denial Rate Reduction', projected: '18%',   realized: '' },
            { type: 'Cash Recovery',         projected: '$2.4M', realized: '' },
          ],
          note: 'Wave 1 payer matrix completed ahead of schedule. Staffing model in review with client VP of Patient Access.',
          noteExport: true,
        },
        {
          id: '10000000-0000-0000-0000-000000000002', title: 'AR aging acceleration – 90+ day bucket remediation',
          workstream: 'ar', status: 'atrisk', owner: 'AR Manager', dueDate: '2026-04-15',
          tasks: [
            { id: 'b1', text: 'Stratify AR aging by payer, service line, and denial reason', done: true,  startDate: '2026-01-06', endDate: '2026-01-23', note: '', owner: 'Marcus Webb', subtasks: [], predecessors: [] },
            { id: 'b2', text: 'Identify systemic billing edits contributing to 90+ day claims', done: true,  startDate: '2026-01-20', endDate: '2026-02-07', note: '', owner: 'Marcus Webb', subtasks: [], predecessors: [] },
            { id: 'b3', text: 'Escalate aged claims over 90 days to payer provider relations teams', done: false, startDate: '2026-02-10', endDate: '2026-03-07', note: 'UHC escalation path unclear – awaiting provider relations contact', owner: 'Marcus Webb', subtasks: [], predecessors: ['b2'] },
            { id: 'b4', text: 'Implement billing edit corrections for top 5 systemic failure codes', done: false, startDate: '2026-02-24', endDate: '2026-03-21', note: '', owner: 'Priya Nair', subtasks: [], predecessors: [] },
            { id: 'b5', text: 'Establish weekly AR velocity tracking cadence and leadership dashboard', done: false, startDate: '2026-03-16', endDate: '2026-04-15', note: '', owner: 'Marcus Webb', subtasks: [], predecessors: ['b3', 'b4'] },
          ],
          impact: [
            { type: 'AR Days Reduction', projected: '4.2 days', realized: '' },
            { type: 'Cash Recovery',     projected: '$3.1M',    realized: '' },
            { type: '',                  projected: '',          realized: '' },
          ],
          note: 'At risk due to delayed payer escalation contacts for UHC and Humana. Escalating to David Marsh for MD-level payer outreach.',
          noteExport: true,
        },
        {
          id: '10000000-0000-0000-0000-000000000003', title: 'Front-end eligibility and clean claim rate improvement',
          workstream: 'access', status: 'inprogress', owner: 'Patient Access Dir.', dueDate: '2026-05-15',
          tasks: [
            { id: 'c1', text: 'Baseline front-end denial rate by category (eligibility, COB, auth not obtained)', done: true,  startDate: '2026-01-06', endDate: '2026-01-23', note: '', owner: 'James Okafor', subtasks: [], predecessors: [] },
            { id: 'c2', text: 'Enable real-time eligibility verification for all scheduled patients T-3 days', done: true,  startDate: '2026-01-27', endDate: '2026-03-07', note: '', owner: 'James Okafor', subtasks: [], predecessors: [] },
            { id: 'c3', text: 'Implement COB verification workflow for dual-eligible population', done: false, startDate: '2026-02-23', endDate: '2026-03-28', note: '', owner: 'James Okafor', subtasks: [], predecessors: [] },
            { id: 'c4', text: 'Train scheduling staff on eligibility exception handling and escalation', done: false, startDate: '2026-03-16', endDate: '2026-04-11', note: '', owner: 'Sarah Callahan', subtasks: [], predecessors: ['c3'] },
            { id: 'c5', text: 'Measure front-end denial rate monthly and report to Access leadership', done: false, startDate: '2026-04-01', endDate: '2026-05-15', note: '', owner: 'James Okafor', subtasks: [], predecessors: [] },
          ],
          impact: [
            { type: 'Clean Claim Rate',      projected: '+94%',  realized: '' },
            { type: 'Denial Rate Reduction', projected: '8.2%', realized: '' },
            { type: 'Cash Recovery',         projected: '$1.1M', realized: '' },
          ],
          note: '', noteExport: false,
        },
        {
          id: '10000000-0000-0000-0000-000000000004', title: 'Medical necessity denial reduction program',
          workstream: 'billing', status: 'notstarted', owner: 'Billing Director', dueDate: '2026-06-01',
          tasks: [
            { id: 'd1', text: 'Pull and validate medical necessity denial data from remittance files', done: false, startDate: '2026-03-03', endDate: '2026-03-21', note: '', owner: 'Priya Nair', subtasks: [], predecessors: [] },
            { id: 'd2', text: 'Stratify denials by payer, DRG, and attending physician', done: false, startDate: '2026-03-17', endDate: '2026-04-04', note: '', owner: 'Priya Nair', subtasks: [], predecessors: ['d1'] },
            { id: 'd3', text: 'Identify top 10 DRGs driving highest medical necessity denial volume', done: false, startDate: '2026-04-06', endDate: '2026-04-25', note: '', owner: 'Priya Nair', subtasks: [], predecessors: ['d2'] },
            { id: 'd4', text: 'Develop CDI query feedback loop with HIM on targeted DRGs', done: false, startDate: '2026-04-21', endDate: '2026-05-15', note: '', owner: 'Sarah Callahan', subtasks: [], predecessors: [] },
            { id: 'd5', text: 'Implement pre-bill medical necessity screening criteria in EHR', done: false, startDate: '2026-05-11', endDate: '2026-06-01', note: '', owner: 'Priya Nair', subtasks: [], predecessors: ['d4'] },
          ],
          impact: [
            { type: 'Denial Rate Reduction', projected: '6.5%',   realized: '' },
            { type: 'Cash Recovery',         projected: '$1.8M',  realized: '' },
            { type: 'AR Days Reduction',     projected: '2.8 days', realized: '' },
          ],
          note: '', noteExport: false,
        },
        {
          id: '10000000-0000-0000-0000-000000000005', title: 'Charge capture and missing charges audit',
          workstream: 'coding', status: 'complete', owner: 'HIM / Coding', dueDate: '2026-03-15',
          tasks: [
            { id: 'e1', text: 'Identify departments with highest DNFB and late charge rates', done: true, startDate: '2026-01-05', endDate: '2026-01-23', note: '', owner: 'Priya Nair', subtasks: [], predecessors: [] },
            { id: 'e2', text: 'Build missing charge detection query against charges and encounter data', done: true, startDate: '2026-01-20', endDate: '2026-02-07', note: '', owner: 'Priya Nair', subtasks: [], predecessors: [] },
            { id: 'e3', text: 'Cross-reference CPT utilization against benchmark comparators by specialty', done: true, startDate: '2026-02-03', endDate: '2026-02-21', note: '', owner: 'Priya Nair', subtasks: [], predecessors: [] },
            { id: 'e4', text: 'Educate clinical departments on charge capture requirements', done: true, startDate: '2026-02-17', endDate: '2026-03-07', note: '', owner: 'Sarah Callahan', subtasks: [], predecessors: [] },
            { id: 'e5', text: 'Implement charge router edits to catch common missed charge patterns', done: true, startDate: '2026-03-02', endDate: '2026-03-15', note: '', owner: 'Priya Nair', subtasks: [], predecessors: [] },
          ],
          impact: [
            { type: 'Cash Recovery',     projected: '$870K', realized: '' },
            { type: 'Clean Claim Rate',  projected: '+3.1%', realized: '' },
            { type: 'AR Days Reduction', projected: '1.9 days', realized: '' },
          ],
          note: 'Completed ahead of schedule. Charge router edits live in Epic as of 3/15. Charge lag improved from 4.2 to 2.3 days on average.',
          noteExport: true,
        },
      ],
      activeFilter: 'all',
      activeRaidTab: 'all',
      tasksFilterWs: 'all',
      tasksFilterStatus: 'all',
      raid: [
        { id: 'r1', type: 'risk', title: 'Payer escalation contacts unavailable for UHC/Humana', description: 'Unable to reach provider relations contacts at UHC and Humana, delaying 90+ day AR escalation.', priority: 'high', status: 'open', owner: 'Marcus Webb', dueDate: '2026-04-01', mitigation: 'Escalate to MD level – David Marsh to leverage payer relationships.', linkedTasks: ['b3'] },
        { id: 'r2', type: 'risk', title: 'Staffing model approval delayed by client HR freeze', description: 'Client HR has a hiring freeze that may delay the FTE approval for centralized auth team.', priority: 'medium', status: 'open', owner: 'Sarah Callahan', dueDate: '2026-03-28', mitigation: 'Explore contract staffing options as interim bridge.', linkedTasks: ['a4'] },
        { id: 'a1', type: 'action', title: 'Schedule weekly AR velocity dashboard review', description: 'Establish recurring weekly meeting with AR Manager to review dashboard metrics.', priority: 'medium', status: 'inprogress', owner: 'Marcus Webb', dueDate: '2026-03-21', mitigation: '', linkedTasks: ['b5'] },
        { id: 'i1', type: 'issue', title: 'COB workflow in Epic not triggering for certain payer combinations', description: 'A subset of dual-eligible patients are not triggering the COB verification workflow due to Epic config issue.', priority: 'high', status: 'open', owner: 'James Okafor', dueDate: '2026-03-15', mitigation: 'Submitted Epic IS ticket. Workaround: manual COB check for flagged payer combos.', linkedTasks: ['c3'] },
      ],
      decisions: [
        { id: 'd1', title: 'Centralize authorization for top 8 specialty areas in Wave 1', description: 'Decision to consolidate auth responsibility into a centralized TAC for Cardiology, Oncology, Orthopedics, Neurology, GI, Pulmonology, Urology, and ENT in the first wave.', status: 'approved', owner: 'Sarah Callahan', date: '2026-01-31', rationale: 'These 8 specialties represent 72% of auth denial volume. Centralization reduces handoff errors and enables consistent payer follow-up.', alternatives: 'Phased by payer vs. by specialty – rejected due to complexity of split ownership.', linkedTasks: ['a3', 'a4'] },
        { id: 'd2', title: 'Use contract staffing bridge for auth team ramp-up', description: 'Approved interim use of contract staff to staff the centralized auth team during the client HR freeze period.', status: 'approved', owner: 'David Marsh', date: '2026-02-14', rationale: 'HR freeze prevents FTE hire before go-live. Contract bridge maintains timeline without sacrificing quality.', alternatives: 'Delay go-live by 6 weeks – rejected as this would push AR impact realization past fiscal year end.', linkedTasks: ['a6'] },
      ],
    },
    {
      config: {
        clientName: 'Project Pinnacle',
        ehr: 'Cerner',
        ehrCustom: '',
        engagementType: 'Implementation',
        projectStatus: 'At Risk',
        startDate: '2025-11-10',
        managingDirector: 'Rachel Torres, Managing Director',
        lead: 'Kevin Adler, Senior Director',
        payers: ['Anthem BCBS', 'Cigna', 'Medicare Advantage', 'Medicaid MCO', 'Aetna'],
        denials: ['Auth Not Obtained', 'Medical Necessity', 'Duplicate Claim', 'Not Covered', 'COB'],
        roles: [
          { key: 'Auth Lead',        clientRole: 'Authorization Supervisor' },
          { key: 'Billing Director', clientRole: 'Director of Revenue Cycle' },
          { key: 'AR Manager',       clientRole: 'Collections Manager' },
          { key: 'Denial Manager',   clientRole: 'Denial Prevention Manager' },
          { key: 'HIM / Coding',     clientRole: 'Coding Supervisor' },
        ],
        workstreams: [
          { id: 'denials',  label: 'Denial Management', color: 'red',    amOwner: 'Kevin Adler' },
          { id: 'billing',  label: 'Billing',            color: 'green',  amOwner: 'Tina Guerrero' },
          { id: 'coding',   label: 'Coding',             color: 'amber',  amOwner: 'Tina Guerrero' },
          { id: 'appeals',  label: 'Appeals',            color: 'purple', amOwner: 'Kevin Adler' },
          { id: 'payer',    label: 'Payer Relations',    color: 'teal',   amOwner: 'Rachel Torres' },
        ],
      },
      milestones: [
        {
          id: '20000000-0000-0000-0000-000000000010', title: 'Denial root cause analysis and segmentation',
          workstream: 'denials', status: 'complete', owner: 'Denial Manager', dueDate: '2026-01-31',
          tasks: [
            { id: 'p1', text: 'Pull 12-month denial data and stratify by CARC/RARC code', done: true, startDate: '2025-11-10', endDate: '2025-11-28', note: '', owner: 'Kevin Adler', subtasks: [], predecessors: [] },
            { id: 'p2', text: 'Identify top 10 denial drivers by dollar volume and frequency', done: true, startDate: '2025-11-24', endDate: '2025-12-12', note: '', owner: 'Kevin Adler', subtasks: [], predecessors: [] },
            { id: 'p3', text: 'Map denial root causes to upstream process owners', done: true, startDate: '2025-12-08', endDate: '2025-12-20', note: '', owner: 'Kevin Adler', subtasks: [], predecessors: [] },
            { id: 'p4', text: 'Present denial segmentation findings to leadership', done: true, startDate: '2026-01-05', endDate: '2026-01-31', note: '', owner: 'Rachel Torres', subtasks: [], predecessors: [] },
          ],
          impact: [
            { type: 'Denial Rate Reduction', projected: 'baseline set', realized: '' },
            { type: 'Cash Recovery',         projected: '$4.7M identified', realized: '' },
            { type: '', projected: '', realized: '' },
          ],
          note: 'Root cause analysis complete. Auth Not Obtained (32%) and Medical Necessity (28%) are the top two drivers.',
          noteExport: true,
        },
        {
          id: '20000000-0000-0000-0000-000000000011', title: 'Auth Not Obtained denial prevention program',
          workstream: 'denials', status: 'atrisk', owner: 'Auth Lead', dueDate: '2026-04-01',
          tasks: [
            { id: 'q1', text: 'Identify procedures requiring auth that currently have no auth workflow', done: true,  startDate: '2026-01-05', endDate: '2026-01-23', note: '', owner: 'Kevin Adler', subtasks: [], predecessors: [] },
            { id: 'q2', text: 'Build payer-specific auth requirement tables in Cerner scheduling', done: false, startDate: '2026-01-27', endDate: '2026-03-06', note: 'Cerner build backlog causing delay – IT ticket submitted 2/3', owner: 'Kevin Adler', subtasks: [], predecessors: [] },
            { id: 'q3', text: 'Implement real-time auth verification alert at point of scheduling', done: false, startDate: '2026-02-23', endDate: '2026-03-21', note: '', owner: 'Kevin Adler', subtasks: [], predecessors: ['q2'] },
            { id: 'q4', text: 'Train scheduling and access staff on new auth verification workflow', done: false, startDate: '2026-03-16', endDate: '2026-04-01', note: '', owner: 'Tina Guerrero', subtasks: [], predecessors: ['q3'] },
          ],
          impact: [
            { type: 'Authorization Rate',    projected: '+15%', realized: '' },
            { type: 'Denial Rate Reduction', projected: '32%',  realized: '' },
            { type: 'Cash Recovery',         projected: '$1.5M', realized: '' },
          ],
          note: 'At risk – Cerner IS build ticket has 6-week backlog. Escalated to Rachel Torres for vendor escalation.',
          noteExport: true,
        },
        {
          id: '20000000-0000-0000-0000-000000000012', title: 'Medical necessity and clinical documentation improvement',
          workstream: 'coding', status: 'inprogress', owner: 'HIM / Coding', dueDate: '2026-05-01',
          tasks: [
            { id: 'r1', text: 'Stratify medical necessity denials by DRG, payer, and attending', done: true,  startDate: '2026-01-05', endDate: '2026-01-23', note: '', owner: 'Tina Guerrero', subtasks: [], predecessors: [] },
            { id: 'r2', text: 'Conduct CDI physician advisor review of top 5 denial DRGs', done: true,  startDate: '2026-01-27', endDate: '2026-02-14', note: '', owner: 'Tina Guerrero', subtasks: [], predecessors: [] },
            { id: 'r3', text: 'Develop CDI query feedback loop with HIM coding team', done: false, startDate: '2026-02-10', endDate: '2026-03-07', note: '', owner: 'Tina Guerrero', subtasks: [], predecessors: [] },
            { id: 'r4', text: 'Implement pre-bill medical necessity screening criteria in Cerner', done: false, startDate: '2026-03-02', endDate: '2026-04-04', note: '', owner: 'Kevin Adler', subtasks: [], predecessors: ['r3'] },
            { id: 'r5', text: 'Measure 60-day post-implementation denial rate change', done: false, startDate: '2026-04-06', endDate: '2026-05-01', note: '', owner: 'Kevin Adler', subtasks: [], predecessors: ['r4'] },
          ],
          impact: [
            { type: 'Denial Rate Reduction', projected: '28%', realized: '' },
            { type: 'Cash Recovery',         projected: '$2.2M', realized: '' },
            { type: 'AR Days Reduction',     projected: '3.5 days', realized: '' },
          ],
          note: '', noteExport: false,
        },
        {
          id: '20000000-0000-0000-0000-000000000013', title: 'Appeals workflow and overturn rate optimization',
          workstream: 'appeals', status: 'inprogress', owner: 'Billing Director', dueDate: '2026-05-15',
          tasks: [
            { id: 's1', text: 'Audit current appeals process and overturn rate by payer and denial category', done: true,  startDate: '2026-01-05', endDate: '2026-01-31', note: '', owner: 'Kevin Adler', subtasks: [], predecessors: [] },
            { id: 's2', text: 'Build denial appeal letter templates by denial category', done: true,  startDate: '2026-02-02', endDate: '2026-02-28', note: '', owner: 'Kevin Adler', subtasks: [], predecessors: [] },
            { id: 's3', text: 'Establish appeals tracking dashboard in Cerner with SLA alerts', done: false, startDate: '2026-02-23', endDate: '2026-03-28', note: '', owner: 'Tina Guerrero', subtasks: [], predecessors: [] },
            { id: 's4', text: 'Train billing staff on new appeals templates and escalation triggers', done: false, startDate: '2026-03-23', endDate: '2026-04-18', note: '', owner: 'Kevin Adler', subtasks: [], predecessors: ['s3'] },
            { id: 's5', text: 'Measure 30-day overturn rate improvement versus baseline', done: false, startDate: '2026-04-20', endDate: '2026-05-15', note: '', owner: 'Kevin Adler', subtasks: [], predecessors: ['s4'] },
          ],
          impact: [
            { type: 'Cash Recovery',     projected: '$1.9M', realized: '' },
            { type: 'AR Days Reduction', projected: '2.1 days', realized: '' },
            { type: '', projected: '', realized: '' },
          ],
          note: '', noteExport: false,
        },
        {
          id: '20000000-0000-0000-0000-000000000014', title: 'Payer contract and reimbursement rate review',
          workstream: 'payer', status: 'notstarted', owner: 'Billing Director', dueDate: '2026-06-30',
          tasks: [
            { id: 't1', text: 'Compile current payer contract terms and fee schedule matrix', done: false, startDate: '2026-04-06', endDate: '2026-04-24', note: '', owner: 'Rachel Torres', subtasks: [], predecessors: [] },
            { id: 't2', text: 'Benchmark reimbursement rates against regional comparators', done: false, startDate: '2026-04-21', endDate: '2026-05-09', note: '', owner: 'Rachel Torres', subtasks: [], predecessors: ['t1'] },
            { id: 't3', text: 'Identify underpayment patterns and short-pay payers', done: false, startDate: '2026-05-05', endDate: '2026-05-23', note: '', owner: 'Kevin Adler', subtasks: [], predecessors: [] },
            { id: 't4', text: 'Develop payer negotiation strategy and talking points for renegotiation', done: false, startDate: '2026-05-19', endDate: '2026-06-30', note: '', owner: 'Rachel Torres', subtasks: [], predecessors: ['t2', 't3'] },
          ],
          impact: [
            { type: 'Cash Recovery',  projected: 'TBD', realized: '' },
            { type: 'Cost Savings',   projected: 'TBD', realized: '' },
            { type: '', projected: '', realized: '' },
          ],
          note: '', noteExport: false,
        },
      ],
      activeFilter: 'all',
      activeRaidTab: 'all',
      tasksFilterWs: 'all',
      tasksFilterStatus: 'all',
      raid: [
        { id: 'rp1', type: 'risk', title: 'Cerner IS build backlog – 6-week delay on auth workflow', description: 'IT ticket submitted 2/3 for auth requirement table build. Current backlog is 6 weeks, pushing go-live.', priority: 'high', status: 'open', owner: 'Kevin Adler', dueDate: '2026-03-15', mitigation: 'Vendor escalation requested through Rachel Torres. Interim manual workflow doc in development.', linkedTasks: ['q2'] },
        { id: 'rp2', type: 'dependency', title: 'CDI physician advisor availability for DRG review', description: 'Medical necessity DRG validation requires physician advisor participation. Availability not yet confirmed.', priority: 'medium', status: 'open', owner: 'Tina Guerrero', dueDate: '2026-02-28', mitigation: 'Coordinate with CMO office to reserve PA time on calendar.', linkedTasks: ['r2'] },
      ],
      decisions: [
        { id: 'dp1', title: 'Prioritize Auth Not Obtained and Medical Necessity as Waves 1 and 2', description: 'Decision to sequence denial prevention work with Auth Not Obtained first (32% of volume) followed by Medical Necessity (28%).', status: 'approved', owner: 'Rachel Torres', date: '2025-12-20', rationale: 'Auth Not Obtained is highest frequency and most process-correctable. Med Nec requires CDI build which has longer lead time.', alternatives: 'Address both simultaneously – rejected due to resource constraints and change management risk.', linkedTasks: ['q1', 'r1'] },
      ],
    },
    {
      config: {
        clientName: 'Project Vertex',
        ehr: 'Meditech',
        ehrCustom: '',
        engagementType: 'Assessment',
        projectStatus: 'On Track',
        startDate: '2026-02-02',
        managingDirector: 'Lisa Park, Managing Director',
        lead: 'Brian Holloway, Director',
        payers: ['Medicare', 'Medicaid', 'BCBS', 'Commercial Mixed'],
        denials: ['Charge Not Covered', 'Medical Necessity', 'Timely Filing', 'Missing Authorization'],
        roles: [
          { key: 'Charge Capture Lead', clientRole: 'Director of Charge Integrity' },
          { key: 'HIM Director',        clientRole: 'VP of Health Information Management' },
          { key: 'CDI Manager',         clientRole: 'CDI Program Manager' },
          { key: 'Coding Manager',      clientRole: 'Coding Operations Manager' },
          { key: 'CFO / Finance',       clientRole: 'SVP of Finance' },
        ],
        workstreams: [
          { id: 'capture',   label: 'Charge Capture',      color: 'blue',   amOwner: 'Brian Holloway' },
          { id: 'coding',    label: 'Coding Accuracy',      color: 'amber',  amOwner: 'Natalie Brooks' },
          { id: 'cdi',       label: 'CDI',                  color: 'teal',   amOwner: 'Natalie Brooks' },
          { id: 'dnfb',      label: 'DNFB / Late Charges',  color: 'coral',  amOwner: 'Brian Holloway' },
          { id: 'benchmark', label: 'Benchmarking',         color: 'purple', amOwner: 'Lisa Park' },
        ],
      },
      milestones: [
        {
          id: '30000000-0000-0000-0000-000000000020', title: 'Missing charge identification and revenue quantification',
          workstream: 'capture', status: 'complete', owner: 'Charge Capture Lead', dueDate: '2026-03-14',
          tasks: [
            { id: 'v1', text: 'Pull charge and encounter data for 12-month lookback period', done: true, startDate: '2026-02-02', endDate: '2026-02-13', note: '', owner: 'Brian Holloway', subtasks: [], predecessors: [] },
            { id: 'v2', text: 'Identify departments with highest DNFB and late charge rates', done: true, startDate: '2026-02-09', endDate: '2026-02-20', note: '', owner: 'Brian Holloway', subtasks: [], predecessors: [] },
            { id: 'v3', text: 'Build missing charge detection logic against charges and encounter data', done: true, startDate: '2026-02-17', endDate: '2026-02-28', note: '', owner: 'Brian Holloway', subtasks: [], predecessors: [] },
            { id: 'v4', text: 'Cross-reference CPT utilization against peer benchmarks by specialty', done: true, startDate: '2026-02-24', endDate: '2026-03-07', note: '', owner: 'Natalie Brooks', subtasks: [], predecessors: [] },
            { id: 'v5', text: 'Quantify total missing charge opportunity and prioritize by department', done: true, startDate: '2026-03-03', endDate: '2026-03-14', note: '', owner: 'Brian Holloway', subtasks: [], predecessors: [] },
          ],
          impact: [
            { type: 'Cash Recovery',    projected: '$2.3M', realized: '' },
            { type: 'Clean Claim Rate', projected: '+4.2%', realized: '' },
            { type: '', projected: '', realized: '' },
          ],
          note: 'Phase 1 complete. $2.3M in annualized missing charge opportunity identified. ED, OR, and Radiology are top three departments.',
          noteExport: true,
        },
        {
          id: '30000000-0000-0000-0000-000000000021', title: 'Coding accuracy and DRG optimization review',
          workstream: 'coding', status: 'inprogress', owner: 'Coding Manager', dueDate: '2026-04-18',
          tasks: [
            { id: 'w1', text: 'Sample and review inpatient coding accuracy across high-volume DRGs', done: true,  startDate: '2026-02-16', endDate: '2026-03-06', note: '', owner: 'Natalie Brooks', subtasks: [], predecessors: [] },
            { id: 'w2', text: 'Identify patterns of undercoding or overcoding by service line', done: true,  startDate: '2026-03-02', endDate: '2026-03-20', note: '', owner: 'Natalie Brooks', subtasks: [], predecessors: [] },
            { id: 'w3', text: 'Conduct physician advisor clinical validation on top 20 denial DRGs', done: false, startDate: '2026-03-16', endDate: '2026-04-03', note: '', owner: 'Natalie Brooks', subtasks: [], predecessors: [] },
            { id: 'w4', text: 'Quantify financial impact of coding accuracy gaps and DRG optimization', done: false, startDate: '2026-03-30', endDate: '2026-04-11', note: '', owner: 'Brian Holloway', subtasks: [], predecessors: ['w3'] },
            { id: 'w5', text: 'Present coding accuracy findings and recommendations to HIM and CFO', done: false, startDate: '2026-04-13', endDate: '2026-04-18', note: '', owner: 'Lisa Park', subtasks: [], predecessors: ['w4'] },
          ],
          impact: [
            { type: 'Cash Recovery',         projected: '$1.4M', realized: '' },
            { type: 'Denial Rate Reduction', projected: '11%', realized: '' },
            { type: '', projected: '', realized: '' },
          ],
          note: 'Preliminary review indicates 14% undercoding rate on cardiac service line. Full DRG validation ongoing.',
          noteExport: true,
        },
        {
          id: '30000000-0000-0000-0000-000000000022', title: 'CDI program effectiveness assessment',
          workstream: 'cdi', status: 'inprogress', owner: 'CDI Manager', dueDate: '2026-04-30',
          tasks: [
            { id: 'x1', text: 'Assess current CDI query rate, response rate, and agreement rate', done: true,  startDate: '2026-02-16', endDate: '2026-02-27', note: '', owner: 'Natalie Brooks', subtasks: [], predecessors: [] },
            { id: 'x2', text: 'Benchmark CDI metrics against AHIMA and peer organization standards', done: true,  startDate: '2026-02-23', endDate: '2026-03-07', note: '', owner: 'Natalie Brooks', subtasks: [], predecessors: [] },
            { id: 'x3', text: 'Identify top DRG pairs where CDI intervention improves severity capture', done: false, startDate: '2026-03-10', endDate: '2026-03-28', note: '', owner: 'Natalie Brooks', subtasks: [], predecessors: [] },
            { id: 'x4', text: 'Develop CDI education program targeting high-opportunity specialties', done: false, startDate: '2026-03-24', endDate: '2026-04-18', note: '', owner: 'Natalie Brooks', subtasks: [], predecessors: ['x3'] },
            { id: 'x5', text: 'Build CDI performance scorecard for ongoing tracking', done: false, startDate: '2026-04-13', endDate: '2026-04-30', note: '', owner: 'Brian Holloway', subtasks: [], predecessors: [] },
          ],
          impact: [
            { type: 'Cash Recovery',         projected: '$900K', realized: '' },
            { type: 'Denial Rate Reduction', projected: '8%', realized: '' },
            { type: 'AR Days Reduction',     projected: '1.7 days', realized: '' },
          ],
          note: '', noteExport: false,
        },
        {
          id: '30000000-0000-0000-0000-000000000023', title: 'DNFB reduction and charge submission timeliness',
          workstream: 'dnfb', status: 'notstarted', owner: 'HIM Director', dueDate: '2026-05-30',
          tasks: [
            { id: 'y1', text: 'Establish DNFB baseline by department and benchmark against peers', done: false, startDate: '2026-04-06', endDate: '2026-04-18', note: '', owner: 'Brian Holloway', subtasks: [], predecessors: [] },
            { id: 'y2', text: 'Identify top contributing departments to late charge volume', done: false, startDate: '2026-04-14', endDate: '2026-04-25', note: '', owner: 'Brian Holloway', subtasks: [], predecessors: ['y1'] },
            { id: 'y3', text: 'Develop charge submission timeliness targets by department and role', done: false, startDate: '2026-04-21', endDate: '2026-05-09', note: '', owner: 'Brian Holloway', subtasks: [], predecessors: [] },
            { id: 'y4', text: 'Build DNFB accountability structure and reporting cadence for leadership', done: false, startDate: '2026-05-04', endDate: '2026-05-30', note: '', owner: 'Lisa Park', subtasks: [], predecessors: ['y2', 'y3'] },
          ],
          impact: [
            { type: 'AR Days Reduction', projected: '3.2 days', realized: '' },
            { type: 'Cash Recovery',     projected: '$750K', realized: '' },
            { type: '', projected: '', realized: '' },
          ],
          note: '', noteExport: false,
        },
        {
          id: '30000000-0000-0000-0000-000000000024', title: 'Executive benchmarking and opportunity summary',
          workstream: 'benchmark', status: 'notstarted', owner: 'CFO / Finance', dueDate: '2026-06-13',
          tasks: [
            { id: 'z1', text: 'Compile all workstream findings into integrated opportunity model', done: false, startDate: '2026-05-18', endDate: '2026-05-29', note: '', owner: 'Lisa Park', subtasks: [], predecessors: [] },
            { id: 'z2', text: 'Benchmark overall revenue cycle performance against national medians', done: false, startDate: '2026-05-25', endDate: '2026-06-05', note: '', owner: 'Lisa Park', subtasks: [], predecessors: ['z1'] },
            { id: 'z3', text: 'Develop prioritized roadmap with ROI, effort, and sequencing', done: false, startDate: '2026-06-01', endDate: '2026-06-10', note: '', owner: 'Brian Holloway', subtasks: [], predecessors: ['z2'] },
            { id: 'z4', text: 'Deliver final assessment presentation to CFO and senior leadership', done: false, startDate: '2026-06-09', endDate: '2026-06-13', note: '', owner: 'Lisa Park', subtasks: [], predecessors: ['z3'] },
          ],
          impact: [
            { type: 'Cash Recovery',     projected: '$5.4M total', realized: '' },
            { type: 'AR Days Reduction', projected: '4.9 days total', realized: '' },
            { type: 'FTE Efficiency',    projected: '8.5 FTEs', realized: '' },
          ],
          note: 'Final deliverable for Phase 1 assessment. Will feed directly into implementation SOW.',
          noteExport: true,
        },
      ],
      activeFilter: 'all',
      activeRaidTab: 'all',
      tasksFilterWs: 'all',
      tasksFilterStatus: 'all',
      raid: [
        { id: 'rv1', type: 'risk', title: 'Limited access to Meditech charge data for 2023 lookback', description: 'IT has not yet granted read access to Meditech charge tables for FY2023. May limit lookback period.', priority: 'medium', status: 'open', owner: 'Brian Holloway', dueDate: '2026-02-20', mitigation: 'Formal data access request submitted. Escalated to SVP Finance.', linkedTasks: ['v1'] },
        { id: 'rv2', type: 'action', title: 'Schedule CDI physician advisor kickoff session', description: 'Need to book physician advisor for CDI DRG pair review – 4-hour working session required.', priority: 'medium', status: 'open', owner: 'Natalie Brooks', dueDate: '2026-03-14', mitigation: '', linkedTasks: ['x3'] },
      ],
      decisions: [
        { id: 'dv1', title: 'Scope assessment to inpatient only for Phase 1', description: 'Decision to limit Phase 1 charge capture and coding assessment to inpatient encounters only. Outpatient to be addressed in Phase 2.', status: 'approved', owner: 'Lisa Park', date: '2026-02-02', rationale: 'Inpatient represents 68% of net revenue and has higher coding complexity. Focused scope produces sharper findings.', alternatives: 'Full inpatient + outpatient scope – rejected due to 12-week timeline constraint.', linkedTasks: ['v1', 'w1'] },
      ],
    },
  ],
};
